import type { Metadata } from "next";
import { Provider } from "./provider";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { auth } from "@/auth";
import { getSessionUser } from "@/lib/session";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = await getSessionUser();
  const isAdmin = user?.role === "admin";

  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} dark`}>
        <Provider session={session}>
          <Navbar isAdmin={isAdmin} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
